logging:
  config: classpath:logback-spring.xml
plumelog:
  appName: plumelog_demo
  redisHost: 125.124.222.34
  redisPort: 63790
  redisAuth: zs94Power
  redisDb: 2
  env: test
spring:
  application:
    name: hydrogen-starter-core-demo
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}